pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo 'Now archiving the artifacts.....'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
            
        }
        stage('Deploy to Staging Env...') {
            steps{
                build job: 'Deploy_Application_Staging_Env'
            }
        }
        stage('Deploy to Production Env...') {
            steps {
                timeout(time:5, units:'DAYS') {
                    input message: 'Approve prod deployment?'
                }
                build job: 'Deploy_Application_Prod_Env'
            }
        }
        
    }
}
